import type { Config } from "tailwindcss";
import { sprintDSColorsHSL } from "./shared/sprint-ds-colors-hsl";

export default {
  darkMode: ["class"],
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        lg: ".5625rem", /* 9px */
        md: ".375rem", /* 6px */
        sm: ".1875rem", /* 3px */
      },
      colors: {
        // Flat / base colors (regular buttons) - Semantic tokens
        background: "hsl(var(--background) / <alpha-value>)",
        foreground: "hsl(var(--foreground) / <alpha-value>)",
        border: "hsl(var(--border) / <alpha-value>)",
        input: "hsl(var(--input) / <alpha-value>)",
        card: {
          DEFAULT: "hsl(var(--card) / <alpha-value>)",
          foreground: "hsl(var(--card-foreground) / <alpha-value>)",
          border: "hsl(var(--card-border) / <alpha-value>)",
        },
        popover: {
          DEFAULT: "hsl(var(--popover) / <alpha-value>)",
          foreground: "hsl(var(--popover-foreground) / <alpha-value>)",
          border: "hsl(var(--popover-border) / <alpha-value>)",
        },
        primary: {
          DEFAULT: "hsl(var(--primary) / <alpha-value>)",
          foreground: "hsl(var(--primary-foreground) / <alpha-value>)",
          border: "var(--primary-border)",
          // CargoSprint DS Primary Color Scale (Teal/Cyan)
          0: `hsl(${sprintDSColorsHSL.primary[0]} / <alpha-value>)`,
          5: `hsl(${sprintDSColorsHSL.primary[5]} / <alpha-value>)`,
          10: `hsl(${sprintDSColorsHSL.primary[10]} / <alpha-value>)`,
          15: `hsl(${sprintDSColorsHSL.primary[15]} / <alpha-value>)`,
          20: `hsl(${sprintDSColorsHSL.primary[20]} / <alpha-value>)`,
          25: `hsl(${sprintDSColorsHSL.primary[25]} / <alpha-value>)`,
          30: `hsl(${sprintDSColorsHSL.primary[30]} / <alpha-value>)`,
          35: `hsl(${sprintDSColorsHSL.primary[35]} / <alpha-value>)`,
          40: `hsl(${sprintDSColorsHSL.primary[40]} / <alpha-value>)`,
          50: `hsl(${sprintDSColorsHSL.primary[50]} / <alpha-value>)`,
          60: `hsl(${sprintDSColorsHSL.primary[60]} / <alpha-value>)`,
          70: `hsl(${sprintDSColorsHSL.primary[70]} / <alpha-value>)`,
          80: `hsl(${sprintDSColorsHSL.primary[80]} / <alpha-value>)`,
          90: `hsl(${sprintDSColorsHSL.primary[90]} / <alpha-value>)`,
          95: `hsl(${sprintDSColorsHSL.primary[95]} / <alpha-value>)`,
          98: `hsl(${sprintDSColorsHSL.primary[98]} / <alpha-value>)`,
          99: `hsl(${sprintDSColorsHSL.primary[99]} / <alpha-value>)`,
          100: `hsl(${sprintDSColorsHSL.primary[100]} / <alpha-value>)`,
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary) / <alpha-value>)",
          foreground: "hsl(var(--secondary-foreground) / <alpha-value>)",
          border: "var(--secondary-border)",
          // CargoSprint DS Secondary Color Scale (Blue)
          0: `hsl(${sprintDSColorsHSL.secondary[0]} / <alpha-value>)`,
          5: `hsl(${sprintDSColorsHSL.secondary[5]} / <alpha-value>)`,
          10: `hsl(${sprintDSColorsHSL.secondary[10]} / <alpha-value>)`,
          15: `hsl(${sprintDSColorsHSL.secondary[15]} / <alpha-value>)`,
          20: `hsl(${sprintDSColorsHSL.secondary[20]} / <alpha-value>)`,
          25: `hsl(${sprintDSColorsHSL.secondary[25]} / <alpha-value>)`,
          30: `hsl(${sprintDSColorsHSL.secondary[30]} / <alpha-value>)`,
          35: `hsl(${sprintDSColorsHSL.secondary[35]} / <alpha-value>)`,
          40: `hsl(${sprintDSColorsHSL.secondary[40]} / <alpha-value>)`,
          50: `hsl(${sprintDSColorsHSL.secondary[50]} / <alpha-value>)`,
          60: `hsl(${sprintDSColorsHSL.secondary[60]} / <alpha-value>)`,
          70: `hsl(${sprintDSColorsHSL.secondary[70]} / <alpha-value>)`,
          80: `hsl(${sprintDSColorsHSL.secondary[80]} / <alpha-value>)`,
          90: `hsl(${sprintDSColorsHSL.secondary[90]} / <alpha-value>)`,
          95: `hsl(${sprintDSColorsHSL.secondary[95]} / <alpha-value>)`,
          98: `hsl(${sprintDSColorsHSL.secondary[98]} / <alpha-value>)`,
          99: `hsl(${sprintDSColorsHSL.secondary[99]} / <alpha-value>)`,
          100: `hsl(${sprintDSColorsHSL.secondary[100]} / <alpha-value>)`,
        },
        tertiary: {
          // CargoSprint DS Tertiary Color Scale (Green)
          // Note: Tertiary doesn't have semantic tokens in index.css, these are direct palette colors
          0: `hsl(${sprintDSColorsHSL.tertiary[0]} / <alpha-value>)`,
          5: `hsl(${sprintDSColorsHSL.tertiary[5]} / <alpha-value>)`,
          10: `hsl(${sprintDSColorsHSL.tertiary[10]} / <alpha-value>)`,
          15: `hsl(${sprintDSColorsHSL.tertiary[15]} / <alpha-value>)`,
          20: `hsl(${sprintDSColorsHSL.tertiary[20]} / <alpha-value>)`,
          25: `hsl(${sprintDSColorsHSL.tertiary[25]} / <alpha-value>)`,
          30: `hsl(${sprintDSColorsHSL.tertiary[30]} / <alpha-value>)`,
          35: `hsl(${sprintDSColorsHSL.tertiary[35]} / <alpha-value>)`,
          40: `hsl(${sprintDSColorsHSL.tertiary[40]} / <alpha-value>)`,
          50: `hsl(${sprintDSColorsHSL.tertiary[50]} / <alpha-value>)`,
          60: `hsl(${sprintDSColorsHSL.tertiary[60]} / <alpha-value>)`,
          70: `hsl(${sprintDSColorsHSL.tertiary[70]} / <alpha-value>)`,
          80: `hsl(${sprintDSColorsHSL.tertiary[80]} / <alpha-value>)`,
          90: `hsl(${sprintDSColorsHSL.tertiary[90]} / <alpha-value>)`,
          95: `hsl(${sprintDSColorsHSL.tertiary[95]} / <alpha-value>)`,
          98: `hsl(${sprintDSColorsHSL.tertiary[98]} / <alpha-value>)`,
          99: `hsl(${sprintDSColorsHSL.tertiary[99]} / <alpha-value>)`,
          100: `hsl(${sprintDSColorsHSL.tertiary[100]} / <alpha-value>)`,
        },
        muted: {
          DEFAULT: "hsl(var(--muted) / <alpha-value>)",
          foreground: "hsl(var(--muted-foreground) / <alpha-value>)",
          border: "var(--muted-border)",
        },
        accent: {
          DEFAULT: "hsl(var(--accent) / <alpha-value>)",
          foreground: "hsl(var(--accent-foreground) / <alpha-value>)",
          border: "var(--accent-border)",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
          border: "var(--destructive-border)",
        },
        error: {
          // CargoSprint DS Error Color Scale (Red)
          // Note: Error doesn't have semantic tokens in index.css, these are direct palette colors
          0: `hsl(${sprintDSColorsHSL.error[0]} / <alpha-value>)`,
          5: `hsl(${sprintDSColorsHSL.error[5]} / <alpha-value>)`,
          10: `hsl(${sprintDSColorsHSL.error[10]} / <alpha-value>)`,
          15: `hsl(${sprintDSColorsHSL.error[15]} / <alpha-value>)`,
          20: `hsl(${sprintDSColorsHSL.error[20]} / <alpha-value>)`,
          25: `hsl(${sprintDSColorsHSL.error[25]} / <alpha-value>)`,
          30: `hsl(${sprintDSColorsHSL.error[30]} / <alpha-value>)`,
          35: `hsl(${sprintDSColorsHSL.error[35]} / <alpha-value>)`,
          40: `hsl(${sprintDSColorsHSL.error[40]} / <alpha-value>)`,
          50: `hsl(${sprintDSColorsHSL.error[50]} / <alpha-value>)`,
          60: `hsl(${sprintDSColorsHSL.error[60]} / <alpha-value>)`,
          70: `hsl(${sprintDSColorsHSL.error[70]} / <alpha-value>)`,
          80: `hsl(${sprintDSColorsHSL.error[80]} / <alpha-value>)`,
          90: `hsl(${sprintDSColorsHSL.error[90]} / <alpha-value>)`,
          95: `hsl(${sprintDSColorsHSL.error[95]} / <alpha-value>)`,
          98: `hsl(${sprintDSColorsHSL.error[98]} / <alpha-value>)`,
          99: `hsl(${sprintDSColorsHSL.error[99]} / <alpha-value>)`,
          100: `hsl(${sprintDSColorsHSL.error[100]} / <alpha-value>)`,
        },
        success: {
          DEFAULT: "hsl(var(--success) / <alpha-value>)",
          foreground: "hsl(var(--success-foreground) / <alpha-value>)",
          border: "var(--success-border)",
          // CargoSprint DS Success Color Scale (Green)
          0: `hsl(${sprintDSColorsHSL.success[0]} / <alpha-value>)`,
          5: `hsl(${sprintDSColorsHSL.success[5]} / <alpha-value>)`,
          10: `hsl(${sprintDSColorsHSL.success[10]} / <alpha-value>)`,
          15: `hsl(${sprintDSColorsHSL.success[15]} / <alpha-value>)`,
          20: `hsl(${sprintDSColorsHSL.success[20]} / <alpha-value>)`,
          25: `hsl(${sprintDSColorsHSL.success[25]} / <alpha-value>)`,
          30: `hsl(${sprintDSColorsHSL.success[30]} / <alpha-value>)`,
          35: `hsl(${sprintDSColorsHSL.success[35]} / <alpha-value>)`,
          40: `hsl(${sprintDSColorsHSL.success[40]} / <alpha-value>)`,
          50: `hsl(${sprintDSColorsHSL.success[50]} / <alpha-value>)`,
          60: `hsl(${sprintDSColorsHSL.success[60]} / <alpha-value>)`,
          70: `hsl(${sprintDSColorsHSL.success[70]} / <alpha-value>)`,
          80: `hsl(${sprintDSColorsHSL.success[80]} / <alpha-value>)`,
          90: `hsl(${sprintDSColorsHSL.success[90]} / <alpha-value>)`,
          95: `hsl(${sprintDSColorsHSL.success[95]} / <alpha-value>)`,
          98: `hsl(${sprintDSColorsHSL.success[98]} / <alpha-value>)`,
          99: `hsl(${sprintDSColorsHSL.success[99]} / <alpha-value>)`,
          100: `hsl(${sprintDSColorsHSL.success[100]} / <alpha-value>)`,
        },
        warning: {
          DEFAULT: "hsl(var(--warning) / <alpha-value>)",
          foreground: "hsl(var(--warning-foreground) / <alpha-value>)",
          border: "var(--warning-border)",
          // CargoSprint DS Warning Color Scale (Orange/Amber)
          0: `hsl(${sprintDSColorsHSL.warning[0]} / <alpha-value>)`,
          5: `hsl(${sprintDSColorsHSL.warning[5]} / <alpha-value>)`,
          10: `hsl(${sprintDSColorsHSL.warning[10]} / <alpha-value>)`,
          15: `hsl(${sprintDSColorsHSL.warning[15]} / <alpha-value>)`,
          20: `hsl(${sprintDSColorsHSL.warning[20]} / <alpha-value>)`,
          25: `hsl(${sprintDSColorsHSL.warning[25]} / <alpha-value>)`,
          30: `hsl(${sprintDSColorsHSL.warning[30]} / <alpha-value>)`,
          35: `hsl(${sprintDSColorsHSL.warning[35]} / <alpha-value>)`,
          40: `hsl(${sprintDSColorsHSL.warning[40]} / <alpha-value>)`,
          50: `hsl(${sprintDSColorsHSL.warning[50]} / <alpha-value>)`,
          60: `hsl(${sprintDSColorsHSL.warning[60]} / <alpha-value>)`,
          70: `hsl(${sprintDSColorsHSL.warning[70]} / <alpha-value>)`,
          80: `hsl(${sprintDSColorsHSL.warning[80]} / <alpha-value>)`,
          90: `hsl(${sprintDSColorsHSL.warning[90]} / <alpha-value>)`,
          95: `hsl(${sprintDSColorsHSL.warning[95]} / <alpha-value>)`,
          98: `hsl(${sprintDSColorsHSL.warning[98]} / <alpha-value>)`,
          99: `hsl(${sprintDSColorsHSL.warning[99]} / <alpha-value>)`,
          100: `hsl(${sprintDSColorsHSL.warning[100]} / <alpha-value>)`,
        },
        info: {
          DEFAULT: "hsl(var(--info) / <alpha-value>)",
          foreground: "hsl(var(--info-foreground) / <alpha-value>)",
          border: "var(--info-border)",
          // CargoSprint DS Info Color Scale (Blue)
          0: `hsl(${sprintDSColorsHSL.info[0]} / <alpha-value>)`,
          5: `hsl(${sprintDSColorsHSL.info[5]} / <alpha-value>)`,
          10: `hsl(${sprintDSColorsHSL.info[10]} / <alpha-value>)`,
          15: `hsl(${sprintDSColorsHSL.info[15]} / <alpha-value>)`,
          20: `hsl(${sprintDSColorsHSL.info[20]} / <alpha-value>)`,
          25: `hsl(${sprintDSColorsHSL.info[25]} / <alpha-value>)`,
          30: `hsl(${sprintDSColorsHSL.info[30]} / <alpha-value>)`,
          35: `hsl(${sprintDSColorsHSL.info[35]} / <alpha-value>)`,
          40: `hsl(${sprintDSColorsHSL.info[40]} / <alpha-value>)`,
          50: `hsl(${sprintDSColorsHSL.info[50]} / <alpha-value>)`,
          60: `hsl(${sprintDSColorsHSL.info[60]} / <alpha-value>)`,
          70: `hsl(${sprintDSColorsHSL.info[70]} / <alpha-value>)`,
          80: `hsl(${sprintDSColorsHSL.info[80]} / <alpha-value>)`,
          90: `hsl(${sprintDSColorsHSL.info[90]} / <alpha-value>)`,
          95: `hsl(${sprintDSColorsHSL.info[95]} / <alpha-value>)`,
          98: `hsl(${sprintDSColorsHSL.info[98]} / <alpha-value>)`,
          99: `hsl(${sprintDSColorsHSL.info[99]} / <alpha-value>)`,
          100: `hsl(${sprintDSColorsHSL.info[100]} / <alpha-value>)`,
        },
        neutral: {
          // CargoSprint DS Neutral Color Scale (Grays)
          0: `hsl(${sprintDSColorsHSL.neutral[0]} / <alpha-value>)`,
          5: `hsl(${sprintDSColorsHSL.neutral[5]} / <alpha-value>)`,
          10: `hsl(${sprintDSColorsHSL.neutral[10]} / <alpha-value>)`,
          15: `hsl(${sprintDSColorsHSL.neutral[15]} / <alpha-value>)`,
          20: `hsl(${sprintDSColorsHSL.neutral[20]} / <alpha-value>)`,
          25: `hsl(${sprintDSColorsHSL.neutral[25]} / <alpha-value>)`,
          30: `hsl(${sprintDSColorsHSL.neutral[30]} / <alpha-value>)`,
          35: `hsl(${sprintDSColorsHSL.neutral[35]} / <alpha-value>)`,
          40: `hsl(${sprintDSColorsHSL.neutral[40]} / <alpha-value>)`,
          50: `hsl(${sprintDSColorsHSL.neutral[50]} / <alpha-value>)`,
          60: `hsl(${sprintDSColorsHSL.neutral[60]} / <alpha-value>)`,
          70: `hsl(${sprintDSColorsHSL.neutral[70]} / <alpha-value>)`,
          80: `hsl(${sprintDSColorsHSL.neutral[80]} / <alpha-value>)`,
          90: `hsl(${sprintDSColorsHSL.neutral[90]} / <alpha-value>)`,
          95: `hsl(${sprintDSColorsHSL.neutral[95]} / <alpha-value>)`,
          98: `hsl(${sprintDSColorsHSL.neutral[98]} / <alpha-value>)`,
          99: `hsl(${sprintDSColorsHSL.neutral[99]} / <alpha-value>)`,
          100: `hsl(${sprintDSColorsHSL.neutral[100]} / <alpha-value>)`,
        },
        'neutral-variant': {
          // CargoSprint DS Neutral Variant Color Scale
          0: `hsl(${sprintDSColorsHSL.neutralVariants[0]} / <alpha-value>)`,
          5: `hsl(${sprintDSColorsHSL.neutralVariants[5]} / <alpha-value>)`,
          10: `hsl(${sprintDSColorsHSL.neutralVariants[10]} / <alpha-value>)`,
          15: `hsl(${sprintDSColorsHSL.neutralVariants[15]} / <alpha-value>)`,
          20: `hsl(${sprintDSColorsHSL.neutralVariants[20]} / <alpha-value>)`,
          25: `hsl(${sprintDSColorsHSL.neutralVariants[25]} / <alpha-value>)`,
          30: `hsl(${sprintDSColorsHSL.neutralVariants[30]} / <alpha-value>)`,
          35: `hsl(${sprintDSColorsHSL.neutralVariants[35]} / <alpha-value>)`,
          40: `hsl(${sprintDSColorsHSL.neutralVariants[40]} / <alpha-value>)`,
          50: `hsl(${sprintDSColorsHSL.neutralVariants[50]} / <alpha-value>)`,
          60: `hsl(${sprintDSColorsHSL.neutralVariants[60]} / <alpha-value>)`,
          70: `hsl(${sprintDSColorsHSL.neutralVariants[70]} / <alpha-value>)`,
          80: `hsl(${sprintDSColorsHSL.neutralVariants[80]} / <alpha-value>)`,
          90: `hsl(${sprintDSColorsHSL.neutralVariants[90]} / <alpha-value>)`,
          95: `hsl(${sprintDSColorsHSL.neutralVariants[95]} / <alpha-value>)`,
          98: `hsl(${sprintDSColorsHSL.neutralVariants[98]} / <alpha-value>)`,
          99: `hsl(${sprintDSColorsHSL.neutralVariants[99]} / <alpha-value>)`,
          100: `hsl(${sprintDSColorsHSL.neutralVariants[100]} / <alpha-value>)`,
        },
        ring: "hsl(var(--ring) / <alpha-value>)",
        chart: {
          "1": "hsl(var(--chart-1) / <alpha-value>)",
          "2": "hsl(var(--chart-2) / <alpha-value>)",
          "3": "hsl(var(--chart-3) / <alpha-value>)",
          "4": "hsl(var(--chart-4) / <alpha-value>)",
          "5": "hsl(var(--chart-5) / <alpha-value>)",
        },
        sidebar: {
          ring: "hsl(var(--sidebar-ring) / <alpha-value>)",
          DEFAULT: "hsl(var(--sidebar) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-foreground) / <alpha-value>)",
          border: "hsl(var(--sidebar-border) / <alpha-value>)",
        },
        "sidebar-primary": {
          DEFAULT: "hsl(var(--sidebar-primary) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-primary-foreground) / <alpha-value>)",
          border: "var(--sidebar-primary-border)",
        },
        "sidebar-accent": {
          DEFAULT: "hsl(var(--sidebar-accent) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-accent-foreground) / <alpha-value>)",
          border: "var(--sidebar-accent-border)"
        },
        status: {
          online: "rgb(34 197 94)",
          away: "rgb(245 158 11)",
          busy: "rgb(239 68 68)",
          offline: "rgb(156 163 175)",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        display: ["var(--font-display)"],
        serif: ["var(--font-serif)"],
        mono: ["var(--font-mono)"],
      },
      fontSize: {
        // Display (Lato)
        'display-lg': ['57px', { lineHeight: '64px', letterSpacing: '-0.25px', fontWeight: '400' }],
        'display-lg-em': ['57px', { lineHeight: '64px', letterSpacing: '-0.25px', fontWeight: '500' }],
        'display-md': ['45px', { lineHeight: '52px', letterSpacing: '0px', fontWeight: '400' }],
        'display-md-em': ['45px', { lineHeight: '52px', letterSpacing: '0px', fontWeight: '500' }],
        'display-sm': ['36px', { lineHeight: '44px', letterSpacing: '0px', fontWeight: '400' }],
        'display-sm-em': ['36px', { lineHeight: '44px', letterSpacing: '0px', fontWeight: '500' }],
        // Headline (Lato)
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '0px', fontWeight: '400' }],
        'headline-lg-em': ['32px', { lineHeight: '40px', letterSpacing: '0px', fontWeight: '500' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '0px', fontWeight: '400' }],
        'headline-md-em': ['28px', { lineHeight: '36px', letterSpacing: '0px', fontWeight: '500' }],
        'headline-sm': ['24px', { lineHeight: '32px', letterSpacing: '0px', fontWeight: '400' }],
        'headline-sm-em': ['24px', { lineHeight: '32px', letterSpacing: '0px', fontWeight: '500' }],
        // Title (Roboto)
        'title-lg': ['22px', { lineHeight: '28px', letterSpacing: '0px', fontWeight: '400' }],
        'title-lg-em': ['22px', { lineHeight: '28px', letterSpacing: '0px', fontWeight: '500' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '0.15px', fontWeight: '400' }],
        'title-md-em': ['16px', { lineHeight: '24px', letterSpacing: '-0.25px', fontWeight: '500' }],
        'title-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '400' }],
        'title-sm-em': ['14px', { lineHeight: '20px', letterSpacing: '-0.1px', fontWeight: '500' }],
        // Body (Roboto)
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '-0.5px', fontWeight: '400' }],
        'body-lg-em': ['16px', { lineHeight: '24px', letterSpacing: '-0.5px', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '-0.25px', fontWeight: '400' }],
        'body-md-em': ['14px', { lineHeight: '20px', letterSpacing: '-0.25px', fontWeight: '500' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '-0.4px', fontWeight: '400' }],
        'body-sm-em': ['12px', { lineHeight: '16px', letterSpacing: '-0.4px', fontWeight: '500' }],
        // Label (Roboto)
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '-0.1px', fontWeight: '400' }],
        'label-lg-em': ['14px', { lineHeight: '20px', letterSpacing: '-0.1px', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '-0.5px', fontWeight: '400' }],
        'label-md-em': ['12px', { lineHeight: '16px', letterSpacing: '-0.5px', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '-0.5px', fontWeight: '400' }],
        'label-sm-em': ['11px', { lineHeight: '16px', letterSpacing: '-0.5px', fontWeight: '500' }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "spin-slow": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "spin-slow": "spin-slow 20s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;
